name: Deploy maxi-lotto-online-web to IIS

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set Environment Variables
      id: set-env
      run: |
        if ("${{ github.ref }}" -eq "refs/heads/main") {
            echo "DEPLOY_ENV=prod" >> $env:GITHUB_ENV
            echo "DEPLOY_SUFFIX=-prod" >> $env:GITHUB_ENV
        } elseif ("${{ github.ref }}" -eq "refs/heads/staging") {
            echo "DEPLOY_ENV=staging" >> $env:GITHUB_ENV
            echo "DEPLOY_SUFFIX=-staging" >> $env:GITHUB_ENV
        } else {
            Write-Error "Unsupported branch for deployment"
            exit 1
        }

    - name: Install Bun
      run: |
        powershell -c "irm bun.sh/install.ps1 | iex"
        echo "$env:USERPROFILE\.bun\bin" >> $env:GITHUB_PATH

    - name: Check Bun
      run: |
        bun --version
        where bun

    - name: Build
      env:
        VITE_SAREPAY_PUBLIC_KEY: ${{ secrets.VITE_SAREPAY_PUBLIC_KEY }}
        VITE_SAREPAY_TOKEN: ${{ secrets.VITE_SAREPAY_TOKEN }}
      run: |
        bun install
        bun run build

    - name: Ensure Target Directories Exist
      run: |
        $baseDir = "C:\inetpub\wwwroot\${{ env.DEPLOY_ENV }}"
        New-Item -ItemType Directory -Force -Path "$baseDir\maxilotto-online-web${{ env.DEPLOY_SUFFIX }}"

    - name: Copy Files to IIS
      run: |
        $baseDir = "C:\inetpub\wwwroot\${{ env.DEPLOY_ENV }}"
        Copy-Item -Path "dist\*" -Destination "$baseDir\maxilotto-online-web${{ env.DEPLOY_SUFFIX }}" -Recurse -Force
